# Generated by Django 2.2.7 on 2019-11-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.TextField(default='default abstract'),
            preserve_default=False,
        ),
    ]
