# Generated by Django 2.2.7 on 2019-11-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
